// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgPNd1WGxe7rglBIkiI1tpGwjxNl7B3BU',
    appId: '1:374836079434:web:f45bf7e7b2f47795b2afb3',
    messagingSenderId: '374836079434',
    projectId: 'malaria-diagnosis-app',
    authDomain: 'malaria-diagnosis-app.firebaseapp.com',
    storageBucket: 'malaria-diagnosis-app.appspot.com',
    measurementId: 'G-VWGFZHEYY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoXCQoYhoj7FTGKlgv__6lPpl8fWhAA5g',
    appId: '1:374836079434:android:4d40b602d3867d79b2afb3',
    messagingSenderId: '374836079434',
    projectId: 'malaria-diagnosis-app',
    storageBucket: 'malaria-diagnosis-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy3C7vuZUBYbVhsdZ0F4bcvUbTFKABG4M',
    appId: '1:374836079434:ios:cecb5bf805ad2137b2afb3',
    messagingSenderId: '374836079434',
    projectId: 'malaria-diagnosis-app',
    storageBucket: 'malaria-diagnosis-app.appspot.com',
    iosBundleId: 'com.example.rbesForMalariaDiagnosis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy3C7vuZUBYbVhsdZ0F4bcvUbTFKABG4M',
    appId: '1:374836079434:ios:cecb5bf805ad2137b2afb3',
    messagingSenderId: '374836079434',
    projectId: 'malaria-diagnosis-app',
    storageBucket: 'malaria-diagnosis-app.appspot.com',
    iosBundleId: 'com.example.rbesForMalariaDiagnosis',
  );
}
